Refatoração para expandir validações e inicializações de objetos nesteados
imobanco/imopay-wrapper pull request #15
Opened 2020-09-21 17:56 UTC by rodrigondec

2020-09-21 20:04 UTC, PedroRegisPOAR requested changes

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/models/test_base.py
> +    def test_get_validation_methods_2(self):
BDD, ta bem abstrato isso.

2020-09-21 20:04 UTC, PedroRegisPOAR commented on imopay_wrapper/models/base.py
> +        data = inspect.getmembers(self, predicate=inspect.ismethod)
Pedacinho de mágica né? Não consegui entender o que exatamente é feito com isso.

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/models/test_base.py
> +    def test_post_init(self):
BDD

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/models/test_base.py
> +    def test_get_validation_methods_1(self):
Esse teste, mesmo juntamente com o outro não ajuda a entender o pq de se ter `item[1] for item in data if "_validate" in item[0]`.

O que é exatamente esse item e o que tem no indice zero e no indice um?

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/models/test_base.py
> +    def test_run_validators_1(self):
BDD

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/validators/test_get_value.py
> +    def test_1(self):
BDD

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/validators/test_get_value.py
> +        obj = MagicMock(foo="bar")
BDD

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/validators/test_get_value.py
> +    def test_3(self):
BDD

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/validators/test_validate_obj_attr_in_collection.py
> +    def test_1(self):
BDD

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/validators/test_validate_obj_attr_in_collection.py
> +    def test_2(self):
BDD

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/validators/test_validate_obj_attr_in_collection.py
> +    def test_3(self):
BDD

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/validators/test_validate_obj_attr_in_collection.py
> +    def test_4(self):
BDD

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/validators/test_validate_obj_attr_type.py
> +    def test_3(self):
BDD

2020-09-21 20:04 UTC, PedroRegisPOAR commented on tests/validators/test_validate_obj_attr_type.py
> +    def test_4(self):
BDD

2020-09-21 20:04 UTC, PedroRegisPOAR commented on imopay_wrapper/models/base.py
> +        pass
It is magic!

2020-09-22 00:04 UTC, rodrigondec commented on imopay_wrapper/models/base.py
> +        data = inspect.getmembers(self, predicate=inspect.ismethod)
Esse daqui foi mágico

2020-09-22 00:05 UTC, rodrigondec commented on tests/models/test_base.py
> +    def test_get_validation_methods_1(self):
O item é uma tupla, onde o primeiro é o nome do atributo, e o segundo é o valor do atributo.

No nosso caso, nome da função e o callable da função!

2020-09-22 00:11 UTC, rodrigondec commented on tests/models/test_base.py
> +    def test_get_validation_methods_2(self):
Done

2020-09-22 00:12 UTC, rodrigondec commented on tests/models/test_base.py
> +    def test_post_init(self):
done

2020-09-22 00:14 UTC, rodrigondec commented on tests/models/test_base.py
> +    def test_run_validators_1(self):
done

2020-09-22 00:18 UTC, rodrigondec commented on tests/validators/test_get_value.py
> +    def test_1(self):
Done

2020-09-22 00:19 UTC, rodrigondec commented on tests/validators/test_get_value.py
> +        obj = MagicMock(foo="bar")
done

2020-09-22 00:19 UTC, rodrigondec commented on tests/validators/test_get_value.py
> +    def test_3(self):
done

2020-09-22 00:27 UTC, rodrigondec commented on tests/validators/test_validate_obj_attr_in_collection.py
> +    def test_1(self):
done

2020-09-22 00:27 UTC, rodrigondec commented on tests/validators/test_validate_obj_attr_in_collection.py
> +    def test_2(self):
done

2020-09-22 00:28 UTC, rodrigondec commented on tests/validators/test_validate_obj_attr_in_collection.py
> +    def test_3(self):
done

2020-09-22 00:28 UTC, rodrigondec commented on tests/validators/test_validate_obj_attr_in_collection.py
> +    def test_4(self):
done

2020-09-22 00:28 UTC, rodrigondec commented on tests/validators/test_validate_obj_attr_type.py
> +    def test_3(self):
done

2020-09-22 00:28 UTC, rodrigondec commented on tests/validators/test_validate_obj_attr_type.py
> +    def test_4(self):
done

2020-09-22 00:33 UTC, PedroRegisPOAR approved these changes

2020-09-22 00:34 UTC, merged