Refatoração das configurações de invoice
imobanco/imopay-wrapper pull request #16
Opened 2020-09-23 19:23 UTC by rodrigondec

2020-09-23 21:21 UTC, PedroRegisPOAR commented on tests/models/transaction/test_configuration.py
> +            - deve ser lançado um FieldError para cada
Completar.

2020-09-23 21:25 UTC, rodrigondec commented on tests/models/transaction/test_configuration.py
> +            - deve ser lançado um FieldError para cada
Done

2020-09-23 21:25 UTC, PedroRegisPOAR approved these changes, later dismissed

2020-09-24 15:30 UTC, PedroRegisPOAR requested changes

2020-09-24 15:30 UTC, PedroRegisPOAR commented on imopay_wrapper/validators.py
> +    Caso strict seja False, data 1 pode ser igual a data 2.
Acho que esse strict esta "perdido" aqui.

2020-09-24 15:30 UTC, PedroRegisPOAR commented on tests/utils.py
> +    return date.today().strftime("%Y-%m-%d")
Esse é o formato YYYY-mm-dd?

2020-09-24 15:30 UTC, PedroRegisPOAR commented on tests/validators/test_validate_date1_gt_date_2.py
> +            - for chamado validate_date_1_gt_date_2("foo", d1, d2)
Pq é necessário esse `foo` como argumento? Só olhando assim não lembro.

2020-09-24 15:30 UTC, PedroRegisPOAR commented on tests/validators/test_validate_date_isoformat.py
> +            - um objeto obj qualquer que tenha foo="2020-08-28"
Aqui ficou claro, mas no outro comantário n.

2020-09-24 15:30 UTC, PedroRegisPOAR commented on tests/wrapper/test_transaction.py
> +                "limit_date": tomorrow(),
Quando Genilson trabalhou na Evolux ele me falou que pegou monte de coisa quebrada por conta de não terem feito as coisas robustas assim em testes que envolviam datas.

2020-09-24 16:19 UTC, rodrigondec commented on tests/utils.py
> +    return date.today().strftime("%Y-%m-%d")
É sim

2020-09-24 16:20 UTC, rodrigondec commented on tests/validators/test_validate_date1_gt_date_2.py
> +            - for chamado validate_date_1_gt_date_2("foo", d1, d2)
seria o nome do argumento que será utilizado pra levantar o erro

2020-09-24 16:22 UTC, rodrigondec commented on imopay_wrapper/validators.py
> +    Caso strict seja False, data 1 pode ser igual a data 2.
done

2020-09-24 16:23 UTC, rodrigondec commented on tests/utils.py
> +    return date.today().strftime("%Y-%m-%d")
adicionei uma docstring

2020-09-24 16:24 UTC, rodrigondec commented on tests/validators/test_validate_date1_gt_date_2.py
> +            - for chamado validate_date_1_gt_date_2("foo", d1, d2)
Adicioneo no BDD

2020-09-24 16:30 UTC, PedroRegisPOAR requested changes

2020-09-24 16:30 UTC, PedroRegisPOAR commented on imopay_wrapper/validators.py
> +    permitido a data de hoje ou ão!
```suggestion
    Com o allow_today é possível flexibilizar se é
    permitido a data de hoje ou não!
```

2020-09-24 16:32 UTC, PedroRegisPOAR approved these changes

2020-09-24 16:32 UTC, merged